"""Prep ALL selected task-362 episodes into official three-tuple clips, then merge
the per-episode clip indexes into one training json + one held-out json.

agibot_finetune_prep.py handles ONE episode -> one json. This driver runs it once
per episode (each into its own clip subdir + own fitted camera), collecting the
per-episode json indexes, and concatenates them:

  train  (20 episodes) -> /mnt/workspace/umi-world-model-lab/datasets/rynnworld-teleop/agibot_362_skel.json          + /mnt/workspace/umi-world-model-lab/datasets/rynnworld-teleop/agibot_362_skel/<eid>/clip_*.safetensors
  heldout (3 episodes) -> /mnt/workspace/umi-world-model-lab/datasets/rynnworld-teleop/agibot_362_skel_heldout.json  + /mnt/workspace/umi-world-model-lab/datasets/rynnworld-teleop/agibot_362_skel_heldout/<eid>/clip_*.safetensors

Why per-episode subprocess (not one long-lived process): each episode needs its own
fitted camera (no intrinsics in AgiBot — see docs/agibot_finetune.md) and isolating
the VAE/ffmpeg per episode keeps GPU memory flat across 20 episodes. The shared task
text embedding (/mnt/workspace/umi-world-model-lab/datasets/rynnworld-teleop/text_embeddings/agibot_task362.safetensors) is generated by the
first prep call and reused by the rest (prep skips it if present).

Held-out episodes are WHOLE unseen episodes (stronger than v2's within-episode tail):
their clips share zero frames with any training episode because they are different
episodes entirely. We still assert episode-id disjointness here.

Usage:
  python scripts/agibot_362_prep_all.py [--max-clips-per-ep 20] [--dry-run]
"""
import argparse
import json
import os
import subprocess
import sys

DL = "/root/autodl-tmp"
SEL = f"{DL}/agibot_362_meta/selection_362.json"
EPISODE_DIR = f"{DL}/agibot_362_data"          # extract output root (observations/ + proprio_stats/)
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PREP = os.path.join(REPO, "scripts", "agibot_finetune_prep.py")
TASK_ID = 362
TASK_TEXT = "Folding shorts"


def prep_one(episode_id, out_dir, camera_out, max_clips, dry_run):
    """Run agibot_finetune_prep.py for one episode. Returns its json index path."""
    cmd = [sys.executable, PREP,
           "--episode-dir", EPISODE_DIR,
           "--task-id", str(TASK_ID),
           "--episode-id", str(episode_id),
           "--task-text", TASK_TEXT,
           "--control-mode", "skeleton",
           "--stride", "81",
           "--max-clips", str(max_clips),
           "--camera-out", camera_out,
           "--output", out_dir]
    print(f"\n=== prep episode {episode_id} -> {out_dir} ===", flush=True)
    print("  " + " ".join(cmd), flush=True)
    if dry_run:
        return f"{out_dir.rstrip('/')}.json"
    subprocess.run(cmd, check=True, cwd=REPO)
    return f"{out_dir.rstrip('/')}.json"


def merge(json_paths, out_json):
    merged = []
    for jp in json_paths:
        if not os.path.exists(jp):
            print(f"  !! missing {jp}, skipping", flush=True)
            continue
        merged.extend(json.load(open(jp)))
    with open(out_json, "w") as f:
        json.dump(merged, f, indent=2)
    print(f"[merged] {len(merged)} clips from {len(json_paths)} episodes -> {out_json}", flush=True)
    return len(merged)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--max-clips-per-ep", type=int, default=20,
                    help="cap clips per episode (stride 81, non-overlapping)")
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()

    sel = json.load(open(SEL))
    train_eps = [str(e) for e in sel["train_episodes"]]
    held_eps = [str(e) for e in sel["heldout_episodes"]]
    assert not (set(train_eps) & set(held_eps)), "train/heldout episode overlap!"
    print(f"task {TASK_ID} '{TASK_TEXT}': {len(train_eps)} train + {len(held_eps)} held-out episodes")

    os.makedirs("/mnt/workspace/umi-world-model-lab/datasets/rynnworld-teleop/text_embeddings", exist_ok=True)
    cam_dir = "/mnt/workspace/umi-world-model-lab/datasets/rynnworld-teleop/agibot_362_cameras"
    os.makedirs(cam_dir, exist_ok=True)

    train_jsons, held_jsons = [], []
    for eid in train_eps:
        jp = prep_one(eid, f"/mnt/workspace/umi-world-model-lab/datasets/rynnworld-teleop/agibot_362_skel/{eid}",
                      f"{cam_dir}/cam_{eid}.npy", a.max_clips_per_ep, a.dry_run)
        train_jsons.append(jp)
    for eid in held_eps:
        jp = prep_one(eid, f"/mnt/workspace/umi-world-model-lab/datasets/rynnworld-teleop/agibot_362_skel_heldout/{eid}",
                      f"{cam_dir}/cam_{eid}.npy", a.max_clips_per_ep, a.dry_run)
        held_jsons.append(jp)

    if a.dry_run:
        print("\n[dry-run] would merge:", train_jsons, held_jsons)
        return
    n_train = merge(train_jsons, "/mnt/workspace/umi-world-model-lab/datasets/rynnworld-teleop/agibot_362_skel.json")
    n_held = merge(held_jsons, "/mnt/workspace/umi-world-model-lab/datasets/rynnworld-teleop/agibot_362_skel_heldout.json")
    print(f"\n[done] train {n_train} clips, held-out {n_held} clips")


if __name__ == "__main__":
    main()
